updates

diff --git a/check b/check
--- a/check
+++ b/check
@@ -6,8 +6,14 @@ die() {
 
 cd "$(dirname "$0")" ||:
 
+# shellcheck disable=SC1091
 . .venv/bin/activate
 
-ruff format --diff || die "ruff failed"
-ruff check || die "ruff failed"
+if [[ -n "$CI" ]]; then
+  ruff format --check || die "ruff format --check failed"
+  ruff check || die "ruff check failed"
+else
+  ruff format || die "ruff format failed"
+  ruff check --fix || die "ruff check --fix failed"
+fi
 mypy . || die "mypy failed"
diff --git a/setup-env b/setup-env
--- a/setup-env
+++ b/setup-env
@@ -14,7 +14,8 @@ if ! [[ -f ".venv/pyvenv.cfg" ]]; then
   python3 -mvenv .venv || die "failed to setup venv"
 fi
 if ! [[ -x ".venv/bin/uv" ]]; then
-  .venv/bin/python -mpip install -U uv || die "failed to setup venv"
+  .venv/bin/python -mpip install -U pip uv || die "failed to setup venv"
 fi
 
-.venv/bin/python -muv pip install -r requirements.txt
+.venv/bin/python -m uv pip install -r requirements.txt
+.venv/bin/python -m pip install -e .
